### ISSUE TITLE
Create templates for lecture 7

### ISSUE THREAD

**Issue by mserykh** [Extenza-Academy/WebDev-100_2021-Q1#27]
Here is a [link to the Lecture 7](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/blob/main/lessons/2-js-basics/4-arrays-loops/README.md)

**Comment by dev-experience** [comment]
> Here is a [link to the Lecture 5](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/blob/main/lessons/2-js-basics/2-functions-methods/README.md)

Why "Lecture 5"?

**Comment by mserykh** [comment]
> > Here is a [link to the Lecture 5](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/blob/main/lessons/2-js-basics/2-functions-methods/README.md)
> 
> Why "Lecture 5"?

I made a mistake. I added content from the lecture 7 to all templates.

**Comment by dev-experience** [comment]
@mserykh
Great! Thanks 👍
