### ISSUE TITLE
1.1. Challenge

### ISSUE THREAD

**Issue by dev-experience** [Extenza-Academy/WebDev-100_2021-Q1#3]
https://github.com/dev-experience/Web-Dev-For-Beginners/tree/main/lessons/1-getting-started-lessons/1-intro-to-programming-languages#-challenge

**Comment by mserykh** [comment]
**JavaScript**: dynamically typed,  interpreted by browser, scripted. language, mostly used for Frontend.
**Java**: statically typed, compiled to bytecode by JVM, mostly used for Backend.

**COBOL**: procedural, imperative, invented in 1959, English-like syntax, which is used to describe nearly everything in a program, used  in business, finance, administrative systems.
**Go**: an open source programming language, announced in 2009,  statically typed.
