### ISSUE TITLE
1.1. Review & self-study

### ISSUE THREAD

**Issue by dev-experience** [Extenza-Academy/WebDev-100_2021-Q1#5]
> Study a bit on the different languages available to the programmer. Try to write a line in one language, and then redo it in two others. What do you learn?

**JS:**
```
const sum = (number1, number2) => {
    return number1 + number2; 
};

const firstSum = sum(4, 9);
console.log(firstSum);
```

**Python:**

```
def sum(number1, number2):
    return number1 + number2

print(sum(4, 9))
```

**Ruby:**

```
def sum(number1, number2) 
     return number1  + number2
end

puts sum(4, 9)
```

https://github.com/dev-experience/Web-Dev-For-Beginners/tree/main/lessons/1-getting-started-lessons/1-intro-to-programming-languages#review--self-study

**Comment by dev-experience** [comment]
Great!

- To be strict, `No. 2`, and `No. 3` don't match `No. 1`. Please fix (without changing `No. 1`).
- Apply proper `Markdown` markup for highlighting the code.
- Help me to verify the task quicker, provide links to online resources to test the code.

@mserykh please fix.

**Comment by mserykh** [comment]
> Study a bit on the different languages available to the programmer. Try to write a line in one language, and then redo it in two others. What do you learn?

**JS**
You can test code in Browser console :)

```javascript
const sum = (number1, number2) => {
    return number1 + number2; 
};

const firstSum = sum(4, 9);
console.log(firstSum);
```

**Python**
You can test code [here](https://repl.it/languages/python3)

```python
def sum(number1, number2):
    return number1 + number2

first_sum = sum(4, 9)
print(first_sum)
```

**Ruby**
You can test code [here](https://repl.it/languages/ruby)

```ruby
def sum(number1, number2) 
     return number1  + number2
end

first_sum = sum(4, 9) 
puts first_sum 
```
