### ISSUE TITLE
1.1. Assignment

### ISSUE THREAD

**Issue by dev-experience** [Extenza-Academy/WebDev-100_2021-Q1#6]
https://github.com/dev-experience/Web-Dev-For-Beginners/tree/main/lessons/1-getting-started-lessons/1-intro-to-programming-languages#assignment

**Comment by mserykh** [comment]
# Tooling #

**Safety Net**: 
- linters: eslint
- source code controls: GitHub, GitLab
- code formatters: Prettier
- bundlers / packages: Parcel, Webpack

**Transformation**:
- babel, PostCSS
- Sass/SCSS, TypeScript, React, Ember, Vue


**Post-development**:
- testing: Jest, Mocha, Jasmine, Travis CI, Jenkins, Circle CI
- deployment: Netlify, Vercel and Github Pages.
- others: getting quality metrics, app uptime monitoring, cross-browser compatibility check (extensions as well).

## My examples ##

**Safety Net**:
-  version control system: [Mercurial](https://www.mercurial-scm.org/guide)
- TypeScript linter: [TSLint](https://palantir.github.io/tslint/)
- Static type checker: [FLOW](https://flow.org/en/docs/getting-started/)

**Transformation**:
- HTML preprocessor: [Pug](https://pugjs.org/api/getting-started.html)

**Post-development**
- Testing: [Sinon.js](https://sinonjs.org/releases/v9.2.2/)
- [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/)
- Web Accessibility Evaluation Tool: [WAVE](https://wave.webaim.org/)

**Comment by dev-experience** [comment]
@mserykh please update the comment based on the assignment expectations:
https://github.com/Extenza-Academy/WebDev-100_2021-Q1/blob/main/lessons/1-getting-started-lessons/1-intro-to-programming-languages/assignment.md#rubric

**Comment by mserykh** [comment]
## My examples ##

**Safety Net**:
-  Version control system: [Mercurial](https://www.mercurial-scm.org/guide) will be used for version tracking, for having full history of changes of the project, both locally and remotely.
- TypeScript linter: [TSLint](https://palantir.github.io/tslint/) will be used for easier way to check code readability, functional errors, keeping track of static types and validating code patterns.
- Static type checker: [FLOW](https://flow.org/en/docs/getting-started/) will be used for checking types to make process of coding faster and easier.

**Transformation**:
- HTML preprocessor: [Pug](https://pugjs.org/api/getting-started.html) will be used to improve code readability and speed of coding, but I think mainly as Pug is a templating framework will be used for Node.ja projects, React projects, for projects when it requires to produce the dynamic HTML web content.

**Post-development**
- Testing: [Sinon.js](https://sinonjs.org/releases/v9.2.2/) will be used for testing JS code: ajax with Fake XMLHttpRequest, behavior of functions,, where faking server is needed, testing time-sensitive logic.
- [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) will be used to analyse how a web page can be improved in terms of UX.
- Web Accessibility Evaluation Tool: [WAVE](https://wave.webaim.org/) will be used to estimate accessibility level of the web-site.
