### ISSUE TITLE
Create templates for part 3: Terrarium

### ISSUE THREAD

**Issue by mserykh** [Extenza-Academy/WebDev-100_2021-Q1#62]
Here is a link to the [part 3](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/tree/main/lessons/3-terrarium). #61

**Comment by mserykh** [comment]
@raybags-web-dev Hey Raymond, could you please not reassign issues that already have been assigned to me or move them to your Board? If you need an issue to do, please create a new issue using "New issue" button in the tab [Issues](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/issues)? Thank you 😊

**Comment by dev-experience** [comment]
@raybags-web-dev I created more issues for you on your Project Board.
So, please just work there: [Raymond's Board](https://github.com/Extenza-Academy/WebDev-100_2021-Q1/projects/3)

If anything is unclear, poke me in Discord please.

**Comment by raybags-web-dev** [comment]
I apologize.
