### ISSUE TITLE
1.1.5. Review & Self-Study

### ISSUE THREAD

**Issue by raybags-web-dev** [Extenza-Academy/WebDev-100_2021-Q1#79]
## Review & Self-Study

Study a bit on the different languages available to the programmer. Try to write a line in one language, and then redo it in two others. What do you learn? 

//Standard function definition is with 'def' while 'function' with javascript
```
def greeting(first_name, last_name) : print( first_name + last_name)
greeting( 'Vince', 'bezos')
```
`const greeting = (first_name, last_name) => console.log( `Hello there my name is ${first_name} ${last_name}` )
`

//Classes in JS 
```
class Person {
        constructor(name, age ){ this.name = name;  this.age   = age; }
        person( name, age ){ console.log( ` ${ this.name = name }  ${ this.age = age }  ` )}
}
let person = new Person('james', 50);

console.log(person.name);
console.log(person.age);`

////Classes in Python 

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)
```

Upon looking into Python, these are the aspects that stood out.
Given the two functions above performing the same operation, Python is more like standard English language, less verbose, does not run in a browser, and of course the syntax is different

**Comment by dev-experience** [comment]
@raybags-web-dev thanks for the comment on the task. Good job!

I have some requests for you, please edit your comment:

- Mention what languages you are comparing before you wrote any code. It's hard to understand, requires some efforts.
- Reformat your code using Markdown.
  - Use proper headings
  - Split separate code snippets (JavaScript and Python should be separate)
  - Combine single code snippet into one
  - To use syntax highlighting do this:
    ``````markdown
    ```javascript
    // JavaScript comment
    console.log('Hello world!');
    ```
    ``````
  - To use backticks (`` ` ``) in the inline code, you can use more than 1 backticks to start the code snippet:
    ```markdown
    ``const greeting = (first_name, last_name) => console.log(`Hello there my name is ${first_name} ${last_name}`)``
    ```

**Comment by dev-experience** [comment]
@raybags-web-dev

1. Please also make your examples identical. At the moment, JavaScript and Python examples are very similar but slightly different. Please update them.

(You can think that it is not so important. But a task is a task 😉)

2. Also, to follow the task definition, provide a third language example for at least one of your examples.
